version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: gizmap-jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - maven_home:/root/.m2
    environment:
      - MAVEN_HOME=/usr/share/maven
      - MAVEN_CONFIG=/root/.m2
    networks:
      - gizmap-network

  postgres:
    image: postgres:15-alpine
    container_name: gizmap-postgres
    environment:
      POSTGRES_DB: gizmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gizmap-network

  app:
    image: gizmap-app
    container_name: gizmap-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gizmap
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - gizmap-network

volumes:
  postgres_data:
  jenkins_home:
  maven_home:

networks:
  gizmap-network:
    driver: bridge
