version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gizmap-postgres
    environment:
      POSTGRES_DB: gizmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gizmap-network

  app:
    build: .
    container_name: gizmap-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gizmap
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - gizmap-network

volumes:
  postgres_data:

networks:
  gizmap-network:
    driver: bridge
